# Generated by Django 5.2 on 2025-04-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
